### ISSUE TITLE
User Resource: Fatal error following #342

### ISSUE THREAD

**Issue by jeherve** [Automattic/wordpress-activitypub#408]
I recently ran into the following fatal error:

```
 PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::get_resource() in /var/www/html/wp-content/plugins/activitypub/includes/class-webfinger.php:33
Stack trace:
#0 /var/www/html/wp-content/plugins/activitypub/includes/functions.php(36): Activitypub\Webfinger::get_user_resource()
#1 /var/www/html/wp-content/plugins/activitypub/includes/class-health-check.php(203): Activitypub\get_webfinger_resource()
#2 /var/www/html/wp-content/plugins/activitypub/includes/class-health-check.php(94): Activitypub\Health_Check::is_webfinger_endpoint_accessible()
#3 /var/www/html/wp-admin/includes/class-wp-site-health.php(194): Activitypub\Health_Check::test_webfinger()
#4 /var/www/html/wp-admin/includes/class-wp-site-health.php(3243): WP_Site_Health->perform_test()
#5 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Site_Health->wp_cron_scheduled_check()
#6 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#7 /var/www/html/wp-includes/plugin.php(565): WP_Hook->do_action()
#8 /var/www/html/wp-cron.php(191): do_action_ref_array()
#9 {main}
  thrown in /var/www/html/wp-content/plugins/activitypub/includes/class-webfinger.php on line 33
```

Maybe we should add a check before trying to get `get_resource`?

*********

I looked at the `get_user_resource` method in the `Webfinger` class, but couldn't immediately understand the way it should work. It references the `get_webfinger_resource`, which in turn comes back to `Webfinger::get_user_resource()`. The references between the 2 plugins can be a bit confusing I think.

**Comment by jeherve** [comment]
Right, but I was running a version that was from just before 7aea1e82636413f6a016a351923dcbf202c289e4, so I didn't have that extra check yet.

**Comment by pfefferle** [comment]
should be fixed now, please re-open if not!
