### ISSUE TITLE
PHP Fatal error:  Uncaught Error / Transformer

### ISSUE THREAD

**Issue by cybeardjm** [Automattic/wordpress-activitypub#818]
### Quick summary

PHP Fatal error:  Uncaught Error: Call to undefined function Activitypub\Transformer\get_sample_permalink() in /srv/data/web/vhosts/<domain>/htdocs/wp-content/plugins/activitypub/includes/transformer/class-post.php:104
Stack trace:
#0 /srv/data/web/vhosts/<domain>/htdocs/wp-content/plugins/activitypub/includes/transformer/class-post.php(91): Activitypub\Transformer\Post->get_url()
#1 [internal function]: Activitypub\Transformer\Post->get_id()
#2 /srv/data/web/vhosts/<domain>/htdocs/wp-content/plugins/activitypub/includes/transformer/class-base.php(63): call_user_func()
#3 /srv/data/web/vhosts/<domain>/htdocs/wp-content/plugins/activitypub/includes/transformer/class-base.php(82): Activitypub\Transformer\Base->transform_object_properties()
#4 /srv/data/web/vhosts/<domain>/htdocs/wp-content/plugins/activitypub/includes/transformer/class-post.php(56): Activitypub\Transformer\Base->to_object()
#5 /srv/data/web/vhosts/<domain>/htdocs/wp-content/plugins/activitypub/includes/transformer/class-base.php(95): Activitypub\Transformer\Post->to_object()
#6 /srv/data/web/vhosts/<domain>/htdocs/wp-content/plugins/activitypub/includes/class-activity-dispatcher.php(83): Activitypub\Transformer\Base->to_activity()
#7 /srv/data/web/vhosts/<domain>/htdocs/wp-includes/class-wp-hook.php(324): Activitypub\Activity_Dispatcher::send_activity()
#8 /srv/data/web/vhosts/<domain>/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#9 /srv/data/web/vhosts/<domain>/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#10 /srv/data/web/vhosts/<domain>/htdocs/wp-content/plugins/activitypub/includes/class-activity-dispatcher.php(204): do_action()
#11 /srv/data/web/vhosts/<domain>/htdocs/wp-includes/class-wp-hook.php(324): Activitypub\Activity_Dispatcher::send_post()
#12 /srv/data/web/vhosts/<domain>/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#13 /srv/data/web/vhosts/<domain>/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#14 /srv/data/web/vhosts/<domain>/htdocs/wp-cron.php(191): do_action_ref_array()
#15 {main}
  thrown in /srv/data/web/vhosts/<domain>/htdocs/wp-content/plugins/activitypub/includes/transformer/class-post.php on line 104

### Steps to reproduce

N/A

### What you expected to happen

N/A

### What actually happened

Found this error in my PHP errorlog. It's the only one so far...

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by janboddez** [comment]
I still see this issue even in the latest version.

As for the fix: adding the leading backslash doesn't really do much; if a function does not exist in the current namespace, PHP will _automatically_ look for a global function (i.e., one defined by, in our case, WP core).

The problem is that the global function `\get_sample_permalink()` _also doesn't exist_. (The error message again including the namespace does not change that fact. The error _always_ includes the namespace; I agree it's confusing.)

The reason, I think, is that core's `wp-admin/includes/post.php` (where said function is defined) is not always loaded. (It's really part of WP-Admin.)

Similar to: https://github.com/WordPress/wordpress-develop/blob/d0566719b39b1ccc88eac525e936b1e29fef5860/src/wp-includes/rest-api/endpoints/class-wp-rest-autosaves-controller.php#L228-L230, we should `require_once` the file containing the missing function:

```
if ( ! function_exists( 'get_sample_permalink' ) ) {
	require_once ABSPATH . 'wp-admin/includes/post.php';
}
```

That is, I didn't actually test this :-D but I'm fairly sure it'd solve the issue?

**Comment by cybeardjm** [comment]
Thx @janboddez - Indeed I saw it appear again, but wasn't sure when I updated, so didn't add to my original comment here.

**Comment by janboddez** [comment]
Oh, it's already fixed in the latest master (?) branch. https://github.com/Automattic/wordpress-activitypub/pull/832
